title: 'Passwords'
methods:
  -
    title: 'Forgot'
    path: '/password_resets'
    method: 'post'
    parameters:
      -
        name: 'email'
        type: 'string'
    example_responses:
      -
        code: 200
        response: >
          {
            "message": "Password reset instructions sent!"
          }
        type: 'json'
      -
        code: 422
        response: >
          {
            "errors": [
              "User with given email not found!"
            ]
          }
        type: 'json'
  -
    title: 'Restore'
    path: '/password_resets'
    method: 'put'
    parameters:
      -
        name: 'code'
        type: 'string'
      -
        name: 'new_password'
        type: 'string'
    example_responses:
      -
        code: 200
        response: >
          {
            "message": "Password updated!"
          }
        type: 'json'
      -
        code: 422
        response: >
          {
            "errors": [
              "User by given code not found!"
            ]
          }
        type: 'json'
